### PR TITLE
Aptitudes as Items, Resolve #7

### LINKED ISSUE #7: Aptitude delete not working properly
asd

### PR DESCRIPTION
**Pull request by aSemy**
Add Aptitudes with a description that can be dragged and dropped onto char sheets.

For testing, make sure that Aptitudes are migrated properly.

Additionally there's a new compendium, so Aptitudes can be easily dragged and dropped onto character sheets.

TODO 

* [x] Migration > convert existing text Aptitudes to new Item Aptitudes

### CODE REVIEW

File: script/sheet/aptitude.js [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+
+    _getHeaderButtons() {
+        let buttons = super._getHeaderButtons();
+        buttons = [].concat(buttons);
+        return buttons;
+    }
+
+    activateListeners(html) {
+        super.activateListeners(html);
+    }
```
Comment (Vindexus) [inline script/sheet/aptitude.js:34]: Really minor thing, but I think these functions could be removed without breaking anything.

Comment (aSemy) [reply script/sheet/aptitude.js:34]: Thanks for having a look!

I see the same code in all .js classes that extend DarkHeresyItemSheet - so these methods can be removed form all of them?

Comment (Vindexus) [reply script/sheet/aptitude.js]: Correct.
